const { withDangerousMod } = require('expo/config-plugins');
const fs = require('fs');
const path = require('path');

/**
 * 在 prebuild 时自动生成 android/local.properties，
 * 避免 --clean 重建后丢失 sdk.dir。
 *
 * SDK 路径优先级：
 *   1. ANDROID_HOME 环境变量
 *   2. ANDROID_SDK_ROOT 环境变量
 *   3. 默认路径（Windows: %LOCALAPPDATA%\Android\Sdk）
 */
function withLocalProperties(config) {
  return withDangerousMod(config, [
    'android',
    (cfg) => {
      const androidRoot = cfg.modRequest.platformProjectRoot;
      const propsPath = path.join(androidRoot, 'local.properties');

      // 如果文件已存在，不覆盖（保留用户手动修改）
      if (fs.existsSync(propsPath)) {
        return cfg;
      }

      const sdkDir =
        process.env.ANDROID_HOME ||
        process.env.ANDROID_SDK_ROOT ||
        path.join(process.env.LOCALAPPDATA || '', 'Android', 'Sdk');

      const content = [
        '## This file is auto-generated by withLocalProperties plugin.',
        `sdk.dir=${sdkDir.replace(/\\/g, '\\\\')}`,
        '',
      ].join('\n');

      fs.writeFileSync(propsPath, content, 'utf-8');
      console.log(`[withLocalProperties] 已生成 ${propsPath} (sdk.dir=${sdkDir})`);
      return cfg;
    },
  ]);
}

module.exports = withLocalProperties;
